spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stock_analysis?currentSchema=stock_analysis
    username: stockanalysisservice
    password: ywY3a2to
  liquibase:
    change-log: file:application/etc/database/changelog.yml
    enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 5000
          fetch_size: 50
        order_inserts: true
  cache:
    type: caffeine
    cache-names: indexIdByIndexName
    caffeine:
      spec: expireAfterWrite=7d


stock-analysis:
  config:
    daily-index:
      folder-path: daily-report/index