INSERT INTO stock_analysis.index (
    i_index_name
)
VALUES
    ('Nifty 50'),
    ('Nifty Next 50'),
    ('Nifty 100'),
    ('Nifty 200'),
    ('Nifty 500'),
    ('Nifty Midcap 50'),
    ('NIFTY Midcap 100'),
    ('NIFTY Smallcap 100'),
    ('Nifty50 Dividend Points'),
    ('Nifty Auto'),
    ('Nifty Bank'),
    ('Nifty Energy'),
    ('Nifty Financial Services'),
    ('Nifty FMCG'),
    ('Nifty IT'),
    ('Nifty Media'),
    ('Nifty Metal'),
    ('Nifty MNC'),
    ('Nifty Pharma'),
    ('Nifty PSU Bank'),
    ('Nifty Realty'),
    ('Nifty India Consumption'),
    ('Nifty Commodities'),
    ('Nifty Dividend Opportunities 50'),
    ('Nifty Infrastructure'),
    ('Nifty PSE'),
    ('Nifty Services Sector'),
    ('Nifty50 Shariah'),
    ('Nifty500 Shariah'),
    ('Nifty Low Volatility 50'),
    ('Nifty Alpha 50'),
    ('Nifty High Beta 50'),
    ('Nifty100 Equal Weight'),
    ('Nifty100 Liquid 15'),
    ('Nifty CPSE'),
    ('Nifty50 Value 20'),
    ('Nifty Midcap Liquid 15'),
    ('Nifty Shariah 25'),
    ('India VIX'),
    ('Nifty Growth Sectors 15'),
    ('Nifty50 TR 1x Inverse'),
    ('Nifty50 TR 2x Leverage'),
    ('Nifty50 PR 1x Inverse'),
    ('Nifty50 PR 2x Leverage'),
    ('NIFTY100 Quality 30'),
    ('Nifty India Corporate Group Index - Mahindra Group'),
    ('Nifty India Corporate Group Index - Aditya Birla Group'),
    ('Nifty India Corporate Group Index - Tata Group'),
    ('Nifty India Corporate Group Index - Tata Group 25% Cap'),
    ('Nifty Private Bank'),
    ('Nifty Smallcap 250'),
    ('Nifty Smallcap 50'),
    ('Nifty Midcap 150'),
    ('Nifty Midcap Select'),
    ('NIFTY LargeMidcap 250'),
    ('NIFTY SME EMERGE'),
    ('Nifty Oil & Gas'),
    ('Nifty Financial Services 25/50'),
    ('Nifty Healthcare Index'),
    ('Nifty500 Multicap 50:25:25'),
    ('Nifty Microcap 250'),
    ('Nifty Total Market'),
    ('Nifty India Digital'),
    ('Nifty Mobility'),
    ('Nifty India Defence'),
    ('Nifty Financial Services Ex-Bank'),
    ('Nifty Housing'),
    ('Nifty Transportation & Logistics'),
    ('Nifty MidSmall Financial Services'),
    ('Nifty MidSmall Healthcare'),
    ('Nifty MidSmall IT & Telecom'),
    ('Nifty MidSmall India Consumption'),
    ('Nifty REITs & InvITs'),
    ('Nifty Core Housing'),
    ('Nifty500 Multicap Infrastructure 50:30:20'),
    ('Nifty Rural'),
    ('Nifty Capital Markets'),
    ('Nifty India New Age Consumption'),
    ('Nifty India Select 5 Corporate Groups (MAATR)'),
    ('Nifty India Railways PSU'),
    ('Nifty Consumer Durables'),
    ('Nifty Non-Cyclical Consumer'),
    ('Nifty500 Multicap India Manufacturing 50:30:20'),
    ('Nifty EV & New Age Automotive'),
    ('Nifty500 LargeMidSmall Equal-Cap Weighted'),
    ('Nifty India Tourism'),
    ('Nifty MidSmallcap 400'),
    ('Nifty IPO'),
    ('Nifty India Internet'),
    ('Nifty Chemicals'),
    ('Nifty Conglomerate 50'),
    ('Nifty India Infrastructure & Logistics'),
    ('Nifty India FPI 150'),
    ('Nifty Waves'),
    ('Nifty Smallcap 500'),
    ('Nifty Cement'),
    ('Nifty REITs & Realty'),
    ('Nifty500 Healthcare'),
    ('Nifty MidSmallcap400 50:50'),
    ('Nifty Total Market Momentum Quality 50'),
    ('Nifty100 Low Volatility 30'),
    ('NIFTY Quality Low-Volatility 30'),
    ('NIFTY Alpha Quality Low-Volatility 30'),
    ('NIFTY Alpha Quality Value Low-Volatility 30'),
    ('NIFTY200 Quality 30'),
    ('NIFTY Midcap150 Quality 50'),
    ('Nifty200 Momentum 30'),
    ('Nifty India Manufacturing'),
    ('Nifty100 ESG Sector Leaders'),
    ('Nifty200 Alpha 30'),
    ('Nifty Midcap150 Momentum 50'),
    ('Nifty Smallcap250 Quality 50'),
    ('Nifty Smallcap250 Momentum Quality 100'),
    ('Nifty MidSmallcap400 Momentum Quality 100'),
    ('Nifty500 Momentum 50'),
    ('Nifty200 Value 30'),
    ('Nifty Top 10 Equal Weight'),
    ('Nifty500 Multicap Momentum Quality 50'),
    ('Nifty Top 15 Equal Weight'),
    ('Nifty Top 20 Equal Weight'),
    ('Nifty500 Quality 50'),
    ('Nifty500 Low Volatility 50'),
    ('NIFTY100 ESG'),
    ('NIFTY100 Enhanced ESG'),
    ('NIFTY500 Value 50'),
    ('NIFTY100 Alpha 30'),
    ('Nifty500 Multifactor MQVLv 50'),
    ('NIFTY Alpha Low-Volatility 30'),
    ('Nifty500 Flexicap Quality 30'),
    ('NIFTY50 Equal Weight'),
    ('Nifty500 Equal Weight'),
    ('Nifty 50 Futures Index'),
    ('Nifty 50 Arbitrage'),
    ('Nifty 50 Futures TR Index'),
    ('Nifty 8-13 yr G-Sec'),
    ('Nifty 4-8 yr G-Sec Index'),
    ('Nifty 11-15 yr G-Sec Index'),
    ('Nifty 15 yr and above G-Sec Index'),
    ('Nifty Composite G-sec Index'),
    ('Nifty 10 yr Benchmark G-Sec'),
    ('Nifty 10 yr Benchmark G-Sec (Clean Price)'),
    ('Nifty BHARAT Bond Index - April 2030'),
    ('Nifty BHARAT Bond Index - April 2031'),
    ('Nifty BHARAT Bond Index - April 2032'),
    ('Nifty BHARAT Bond Index - April 2033'),
    ('Nifty 1D Rate Index'),
    ('Nifty50 USD'),
    ('Nifty Commercial & Transport Services'),
    ('Nifty Next 100'),
    ('Nifty NBFC'),
    ('Nifty Small Finance Banks & Microfinance Institutions'),
    ('Nifty Construction'),
    ('Nifty Hospitals'),
    ('Nifty Housing Finance'),
    ('Nifty Insurance'),
    ('Nifty Power'),
    ('Nifty Retail'),
    ('Nifty Consumer Services'),
    ('Nifty Capital Goods'),
    ('Nifty Telecommunications'),
    ('Nifty Sugar & Ethanol'),
    ('Nifty500 Ahimsa'),
    ('Nifty REITs & InvITs 90:10'),
    ('Nifty500 Growth 50'),
    ('Nifty India Defence Equal Weight')
ON CONFLICT (i_index_name) DO NOTHING;