name: Release Stock Analysis Service

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    uses: ./.github/workflows/common.yml

  release:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags --force

      - name: Run release
        run: ./gradlew release -Prelease.versionIncrementer=incrementMinor